In [2]:
!pip install matplotlib

     |████████████████████████████████| 11.3 MB 1.4 MB/s eta 0:00:01
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
     |████████████████████████████████| 1.2 MB 1.5 MB/s eta 0:00:01
  Using cached fonttools-4.33.3-py3-none-any.whl (930 kB)


In [20]:
#import required packages
import gym 
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output

In [6]:
!pip install pygame

     |████████████████████████████████| 21.8 MB 1.1 MB/s eta 0:00:01


In [7]:
env = gym.make('Taxi-v3')

In [63]:
import time
episodes = 10
for episode in range (1, episodes):
    time.sleep(2)
    state = env.reset()
    done = False
    score = 0
    
    
    while not done:
        clear_output(wait = True)
        time.sleep(0.4)
        env.render()
        state, reward, done, info = env.step(env.action_space.sample())
        score += reward
        
        
    print(f'Episode: {episode}\nScore: {score}')
    
env.close()
        

KeyboardInterrupt: 

In [45]:
# creating q table 

actions = env.action_space.n
state = env.observation_space.n

q_table = np.zeros((state, actions))

In [55]:
#parameters for q learning

num_episodes = 10000
max_steps_per_episode = 1000
learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

rewards_all_episodes = []

In [56]:
# Q learning algorithm

for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
        #exploration vs exploitation trade off
        exploration_threshold = np.random.uniform(0, 1)
        
        if exploration_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        # Update q table
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        
        state = new_state 
        rewards_current_episode += reward
        
        if done:
            break
    exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    
    rewards_all_episodes.append(rewards_current_episode)
    
    
print('training_completed')

training_completed


In [57]:
print(q_table)

[[ 0.          0.          0.          0.          0.          0.        ]
 [ 7.43253877  8.52362866  7.43055204  8.5175642   9.6220697  -0.48199078]
 [11.82494447 12.95983049 11.84156747 12.96235425 14.11880599  3.9755022 ]
 ...
 [14.10542167 15.2715212  14.11753358 12.95386852  5.11402848  5.11322485]
 [ 7.85562345  9.27426129  7.47744081 10.7231212  -0.82878704 -1.07528418]
 [15.65417417 14.19826742 16.33221638 18.7999473   7.60486105  7.62282112]]


In [58]:
# calculate and print average reward per thousand episodes


rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes / 1000)
count = 1000

print("Average per thousand episodes")


for r in rewards_per_thousand_episodes:
    print(f'{count} : {sum(r/1000)}')
    count += 1000


Average per thousand episodes
1000 : -187.79300000000012
2000 : -8.82
3000 : 2.7999999999999905
4000 : 5.652999999999967
5000 : 6.852999999999968
6000 : 7.099999999999973
7000 : 7.282999999999958
8000 : 7.238999999999971
9000 : 7.553999999999963
10000 : 7.476999999999957


In [64]:
# visualize agent

import time

for episode in range(3):
    state = env.reset()
    done = False
    
    
    print(f'Episode is: {episode}')
    time.sleep(1)
    
    
    for step in range(max_steps_per_episode):
        clear_output(wait = True)
        env.render()
        time.sleep(0.4)
        action = np.argmax(q_table[state, :])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait = True)
            env.render()
            
            if reward == 1:
                print('reached goal')
                clear_output(wait = True)
                time.sleep(2)
                
            else:
                print('Failed')
                clear_output(wait = True)
                time.sleep(2)
                
            break
        state = new_state
        
env.close()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
Failed
